### ISSUE TITLE
Garbled text with chesthole tileset

### ISSUE THREAD

**Issue by Hotline-Dave** [a1studmuffin/Cataclysm-DDA-Android#50]
When using the chesthole tileset text is garbled, only when using hardware  acceleration. When using software rendering the text works fine, but the application crashes every time it switches to landscape, either through sensor or being set in the options menu. 

On oneplus 2
With oxygen OS 3.5.8
Android 6.0.1

**Comment by Dyrewulfe** [comment]
The hardware rendering text problem seems to be a driver issue with Android 6.0.1. I don't think we can fix that.

If you start the game with your device in landscape orientation, you can then set landscape in the options(slide left, not right!), save it, and be good to go from there on. I've recently acquired a device which has the crash-on-rotating issue, and hopefully will be able to get that fully resolved now.

**Comment by Hotline-Dave** [comment]
The garbled text only occurs with the chesthole tileset, all the others work fine.

**Comment by Dyrewulfe** [comment]
Hmmm. Something you could try would be to change all your fonts to Terminus. It might just make the Chesthole sets work for you, and if it does, it would also verify the source of that glitch(if it's what I think it i, I can fix it, it'll just take some work.)

Would you be willing to place the linked file in Android/data/com.MichaelDavies.CataclysmDDA/files/config, and let me know if the Chesthole tileset works for you with hardware rendering?

https://www.dropbox.com/s/r3ktw1o7lsx197q/fonts.json?dl=0

**Comment by Hotline-Dave** [comment]
Sure

**Comment by Hotline-Dave** [comment]
No dice, I still get the garbled text with chesthole, thanks for trying though.

**Comment by Dyrewulfe** [comment]
Well, thank you. Not the answer I was expecting, but the information is much appreciated.

**Comment by Dyrewulfe** [comment]
Closing: This is device & Android version specific. Fixing requires changes to mainstream(or an Android version update)
